title: "Domus"
author: "Anshuman Barnwal"
# description: 'Made with <b style="color: #f45;">&lt;3</b>'
description: "Godot Gains"
permalink: /:year/:month/:title/
lang: "en"
excerpt_separator: "<!---->"
date_format: "%B %d, %Y"
paginate: 5
paginate_path: /page/:num/

# Layout

show_excerpts: true # show article excerpts on the home page
show_frame: true # adds a gray frame to the site
show_sidebar: true # show a sidebar instead of the usual header
show_title: true
show_related: true # show previous and next posts
minimal: true # use a dark header
mathjax: true
markdown: kramdown

# Menu

navigation: # accepts {file, title, url, icon, sidebaricon}
  - { file: "index.html", icon: home }
  - { file: "blogs.html" }
  - { file: "about.md" }
  - { file: "contact.html" }
  # - { file: "archive.html" }
  # - { file: "README.md" }

external: # shows a footer with social links - for available icons see fontawesome.com/icons
  - { title: Mail, icon: envelope, url: "mailto:b.anshuman1305@gmail.com" }
  - { title: Github, icon: github, url: "https://github.com/ba-13" }
  - {
      title: LinkedIn,
      icon: linkedin,
      url: "https://www.linkedin.com/in/anshumanbarnwal",
    }
  - {
      title: StackOverflow,
      icon: stack-overflow,
      url: "https://stackoverflow.com/users/14015559/ba-13",
    }
  - {
      title: Instagram,
      icon: instagram,
      url: "https://www.instagram.com/human_b.a/",
    }
  - { title: Subscribe, icon: rss, url: "/feed.xml" }

comments:
  disqus_shortname: "ba-13-github-io" # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
